### ISSUE TITLE
Klarna checkout Krokedil plugin issue with shipping 

### ISSUE THREAD

**Issue by nickfoutr** [krokedil/krokedil-checkout-customizer-for-woocommerce#1]
Hey
I have got an issue the last 3 days with Klarnas plugin in woocommerce. When you are in the the checkout in the website although you see the shipping cost, Klarna doesn't include it in the plugin. And then is creating the order in Klarnas backend without the shipping fee. In woocommerce panel you seer the order with the shipping fee, but not in Klarna. It must be something with the callback. 

Can someone from Krokedil help please?

Nick

**Comment by NiklasHogefjord** [comment]
Hi Nick,
You have created an issue in a repository that is not a Klarna-plugin.

You can grab the latest version of the Klarna v2-plugin (version 2.6.0) here: https://github.com/krokedil/woocommerce-gateway-klarna/releases. Version 2.6.0 should fix the problem you're experiencing.

**Comment by nickfoutr** [comment]
Hey Niklas!

Thank you for your quick response. Will I add the files in the same folder via ftp in my hosting files? Or do I need to do something else to install it?

**Comment by nickfoutr** [comment]
it doesn't seems to work the update.

**Comment by NiklasHogefjord** [comment]
Send a support ticket to support@krokedil.se together with a WP admin login and we will have a closer look.

**Comment by nickfoutr** [comment]
I have sent an email with the credentials in support
